Birthday_date1 = input("Enter your birthday date:")
print("Your birthday date is:", Birthday_date1)
Birthday_date2 = input("Eneter another birthday date:")
print("Your friend's birthday date is:", Birthday_date2)
Birthday_date3 = input("Eneter another birthday date:")
print("Your friend's birthday date is:", Birthday_date3)
Birthday_date4 = input("Eneter another birthday date:")
print("Your friend's birthday date is:", Birthday_date4)
Birthday_date5 = input("Eneter another birthday date:")
print("Your friend's birthday date is:", Birthday_date5)